# Generated by Django 6.0.6 on 2026-06-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='lien_demo',
            field=models.URLField(blank=True),
        ),
        migrations.RemoveField(
            model_name='projet',
            name='technologies',
        ),
        migrations.AddField(
            model_name='projet',
            name='technologies',
            field=models.ManyToManyField(related_name='projets', to='projets.technologie'),
        ),
    ]
