# Generated by Django 6.0.6 on 2026-06-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_technologie_projet_lien_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
