# Generated by Django 6.0.6 on 2026-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0003_projet_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projet',
            options={'ordering': ['-id'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AlterModelOptions(
            name='technologie',
            options={'ordering': ['nom'], 'verbose_name': 'Technologie', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='projet',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='lien_demo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projet',
            name='lien_github',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projet',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projets', to='projets.technologie'),
        ),
        migrations.AlterField(
            model_name='technologie',
            name='nom',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
